[project]
name = "passuth"
version = "0.1.0"
authors = [{ name = "Dowon", email = "ks2515@naver.com" }]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
keywords = ["password", "argon2"]
dependencies = []

[dependency-groups]
dev = ["ruff", "pre-commit-uv"]
test = ["pytest", "pytest-pretty", "hypothesis"]

[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]

[tool.uv]
default-groups = "all"
